apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
  labels:
    app: user-api
spec:
  selector:
    matchLabels:
      app: user-api
  replicas: 2
  template:
    metadata:
      labels:
        app: user-api
    spec:
      volumes:
      - name: rsa-keys
        secret:
          secretName: rsa-keys
      containers:
      - name: user-api
        image: userapi:local
        imagePullPolicy: IfNotPresent
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: LocalDocker
        - name: ConnectionStrings__MongoDB
          value: "mongodb://mongo-db.default.svc.cluster.local:27017"
        ports:
        - containerPort: 80
          name:  http
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: http
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: http
        volumeMounts:
        - name: rsa-keys
          mountPath: /keys