version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - checkout
      - run:
          name: build
          command: |
            dotnet build .
  unit-tests:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - checkout
      - run:
          name: unit-tests
          command: |
            dotnet test tests/UserAPI.Infrastructure.UnitTests
  docker-build:
    machine:
      image: ubuntu-2004:202111-01
    steps:
      - checkout
      - run docker build . -f src/UserAPI.Host/Dockerfile
  e2e-tests:
    machine:
      image: ubuntu-2004:202111-01
    working_directory: ~/app/docker-compose
    steps:
      - checkout:
          path: ~/app
      - run: docker-compose -f docker-compose.yaml -f docker-compose-e2e-tests.yaml up --build -d
      - run:
          name: e2e-tests
          when: always
          command: |
            docker logs mongo-db-data-seed
            docker logs user-api
            docker logs e2e-tests --follow
            export TESTS_EXIT_CODE=$(docker wait e2e-tests)
            exit $TESTS_EXIT_CODE
      - run: docker-compose -f docker-compose.yaml -f docker-compose-e2e-tests.yaml down

  release:
    docker:
      - image: cimg/node:16.13.1
    steps:
      - checkout
      - run: npm install semantic-release@18.0.1
      - run: npx semantic-release --debug

workflows:
  userapi-workflow:
    jobs:
      - build
      - unit-tests:
          requires:
            - build
          filters:
            branches:
              ignore: /docs\/.*/
      - docker-build:
          requires:
            - build
          filters:
            branches:
              ignore: /docs\/.*/
      - e2e-tests:
          requires:
            - build
            - unit-tests
            - docker-build
          filters:
            branches:
              ignore: /docs\/.*/
      - release:
          requires:
            - e2e-tests
          filters:
            branches:
              only: dev
