version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - checkout
      - run:
          name: build
          command: |
            dotnet build .
  unit-tests:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - checkout
      - run:
          name: unit-tests
          command: |
            dotnet test tests/UserAPI.Infrastructure.UnitTests
  e2e-tests:
    machine: true
    steps:
      - checkout:
          path: docker-compose
      - run: docker-compose -f docker-compose.yaml -f docker-compose-e2e-tests.yaml up --build


workflows:
  userapi-workflow:
    jobs:
      - build
      - unit-tests
      - e2e-tests
