version: "3.0"

services:

  mongo-db:
    image: mongo:latest
    ports:
      - 27017:27017
  
  user-api:
    image: userapi:1.0
    build:
      context: ../
      dockerfile: src/UserAPI.Host/Dockerfile
    depends_on:
      - mongo-db
    ports:
      - 80:80