version: "3.0"

services:

  mongo-db:
    container_name: mongo-db
    image: mongo:latest
    ports:
      - 27017:27017

  mongo-db-data-seed:
    container_name: mongo-db-data-seed
    image: mongo:latest
    command: bash -c "mongo mongo-db/UserAPI /scripts/mongo-data-seed.js"
    volumes:
      - ./scripts:/scripts
    depends_on:
      - mongo-db
  
  user-api:
    container_name: user-api
    image: userapi:local
    build:
      context: ../
      dockerfile: src/UserAPI.Host/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=LocalDocker
    volumes:
      - ../.keys:/keys
    depends_on:
      - mongo-db-data-seed
    ports:
      - 50000:80