version: "3.0"

services:

  e2e-tests:
    container_name: userapi-e2e-tests
    image: userapi-e2e:local
    build:
      context: ../
      dockerfile: tests/UserAPI.E2E/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=LocalDocker
    depends_on:
      - user-api